# Generated by Django 4.1.2 on 2022-11-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cazare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('author', models.EmailField(blank=True, default=None, max_length=100, null=True)),
                ('adresa', models.URLField(blank=True, default=None, max_length=100, null=True)),
                ('photos', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
        ),
    ]
