# Generated by Django 4.1.2 on 2022-11-22 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cazare',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
